-- Drop and recreate statements generated by Prisma Migrate equivalent
ALTER TABLE "Booking"
ADD COLUMN "managementToken" TEXT,
ADD COLUMN "managementTokenExpiresAt" TIMESTAMP(3);

CREATE UNIQUE INDEX "Booking_managementToken_key" ON "Booking"("managementToken");
